import { githubAppService } from '@/services/github-app';
import { db } from '@/lib/db';

export interface SyncResult {
  repoId: string;
  repoFullName: string;
  status: 'SUCCESS' | 'FAILED';
  branch?: string;
  prUrl?: string;
  error?: string;
}

export interface SyncSummary {
  succeeded: SyncResult[];
  failed: SyncResult[];
}

export class SyncService {
  /**
   * Sync a spec to all repos in a project (best-effort)
   */
  async syncToRepos(
    specRevId: string,
    projectId: string
  ): Promise<SyncSummary> {
    const specRev = await db.specRevision.findUnique({
      where: { id: specRevId },
      include: {
        feature: {
          include: {
            project: {
              include: {
                repos: true,
              },
            },
          },
        },
      },
    });

    if (!specRev) {
      throw new Error('Spec revision not found');
    }

    const project = specRev.feature.project;
    const repos = project.repos;

    if (repos.length === 0) {
      throw new Error('No repositories attached to this project');
    }

    const results: SyncResult[] = [];

    // Try syncing to each repo (best-effort, continue on failures)
    for (const repo of repos) {
      try {
        const result = await this.syncToRepo(specRevId, repo.id);
        results.push(result);
      } catch (error) {
        results.push({
          repoId: repo.id,
          repoFullName: repo.fullName,
          status: 'FAILED',
          error:
            error instanceof Error ? error.message : 'Unknown error occurred',
        });
      }
    }

    // Categorize results
    const succeeded = results.filter((r) => r.status === 'SUCCESS');
    const failed = results.filter((r) => r.status === 'FAILED');

    // If at least one succeeded, mark feature as HANDED_OFF
    if (succeeded.length > 0) {
      await db.feature.update({
        where: { id: specRev.featureId },
        data: { status: 'HANDED_OFF' },
      });

      // Lock the spec revision
      await db.specRevision.update({
        where: { id: specRevId },
        data: {
          status: 'HANDED_OFF',
          isActive: false,
        },
      });
    }

    return { succeeded, failed };
  }

  /**
   * Sync a spec to a single repo
   */
  private async syncToRepo(
    specRevId: string,
    repoId: string
  ): Promise<SyncResult> {
    const specRev = await db.specRevision.findUnique({
      where: { id: specRevId },
      include: {
        feature: {
          include: {
            project: true,
          },
        },
      },
    });

    const repo = await db.repoAttachment.findUnique({
      where: { id: repoId },
    });

    if (!specRev || !repo) {
      throw new Error('Spec revision or repo not found');
    }

    const feature = specRev.feature;
    const project = feature.project;

    try {
      // Step 1: Get GitHub installation token
      const token = await githubAppService.getInstallationToken(
        project.orgId,
        repo.fullName
      );

      // Step 2: Get repo info (default branch SHA)
      const repoInfo = await githubAppService.getRepoInfo(
        token,
        repo.fullName
      );

      // Step 3: Create branch
      const branch = specRev.branchName;
      await githubAppService.createBranch(
        token,
        repo.fullName,
        branch,
        repoInfo.defaultBranchSha
      );

      // Step 4: Commit spec files
      const specFiles = this.prepareSpecFiles(feature, specRev);
      const commitSha = await githubAppService.commitFiles(
        token,
        repo.fullName,
        branch,
        specFiles,
        `Add specification for ${feature.title}\n\nGenerated by SpecForge Portal\nFeature ID: ${feature.id}\nSpec Revision: ${specRev.revNumber}`
      );

      // Step 5: Create PR
      const prUrl = await githubAppService.createPullRequest(
        token,
        repo.fullName,
        branch,
        repo.defaultBranch,
        `Spec: ${feature.title}`,
        this.generatePRBody(feature, specRev, project.name)
      );

      // Step 6: Save sync record
      await db.repoSyncRecord.create({
        data: {
          specRevId,
          repoId,
          featureId: feature.id,
          branch,
          commitSha,
          prUrl,
          syncStatus: 'PR_OPEN',
          syncedAt: new Date(),
        },
      });

      return {
        repoId,
        repoFullName: repo.fullName,
        status: 'SUCCESS',
        branch,
        prUrl,
      };
    } catch (error) {
      // Record failure in database
      await db.repoSyncRecord.create({
        data: {
          specRevId,
          repoId,
          featureId: feature.id,
          branch: specRev.branchName,
          syncStatus: 'FAILED',
          errorMessage:
            error instanceof Error ? error.message : 'Unknown error',
        },
      });

      throw error;
    }
  }

  /**
   * Prepare spec files for commit
   */
  private prepareSpecFiles(
    feature: any,
    specRev: any
  ): Array<{ path: string; content: string }> {
    const featureDir = `specs/feature-${feature.id.slice(-8)}`;

    // Note: In a real implementation, you'd fetch the actual spec content
    // For now, we'll create placeholder content
    const specContent = `# Feature Specification: ${feature.title}

${feature.description || ''}

**Generated by SpecForge Portal**
**Feature ID**: ${feature.id}
**Spec Revision**: ${specRev.revNumber}
**Branch**: ${specRev.branchName}

This specification was automatically generated and synced from the SpecForge portal.
`;

    return [
      {
        path: `${featureDir}/spec.md`,
        content: specContent,
      },
      {
        path: `${featureDir}/README.md`,
        content: `# ${feature.title}

This directory contains the specification for the "${feature.title}" feature.

- **spec.md**: Complete feature specification
- **plan.md**: Implementation plan (to be generated)
- **tasks.md**: Task breakdown (to be generated)

Generated by SpecForge Portal on ${new Date().toISOString().split('T')[0]}
`,
      },
    ];
  }

  /**
   * Generate PR body with links back to portal
   */
  private generatePRBody(
    feature: any,
    specRev: any,
    projectName: string
  ): string {
    return `## Specification: ${feature.title}

**Project**: ${projectName}
**Feature Status**: ${feature.status}
**Spec Revision**: r${specRev.revNumber}

### Description

${feature.description || 'No description provided.'}

### Specification Files

This PR adds the following specification files:
- \`specs/feature-${feature.id.slice(-8)}/spec.md\` - Complete feature specification
- \`specs/feature-${feature.id.slice(-8)}/README.md\` - Directory overview

### Next Steps

1. Review the specification for completeness and clarity
2. Generate implementation plan and tasks
3. Begin development according to the spec
4. Update status in SpecForge portal once development starts

---

🤖 Generated automatically by [SpecForge Portal](${process.env.NEXT_PUBLIC_APP_URL || 'http://localhost:3000'})
`;
  }

  /**
   * Get sync status for a feature
   */
  async getSyncStatus(featureId: string): Promise<SyncResult[]> {
    const syncRecords = await db.repoSyncRecord.findMany({
      where: { featureId },
      include: {
        repo: true,
      },
      orderBy: {
        syncedAt: 'desc',
      },
    });

    return syncRecords.map((record) => ({
      repoId: record.repoId,
      repoFullName: record.repo.fullName,
      status: record.syncStatus === 'FAILED' ? 'FAILED' : 'SUCCESS',
      branch: record.branch,
      prUrl: record.prUrl || undefined,
      error: record.errorMessage || undefined,
    }));
  }
}

export const syncService = new SyncService();
